version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/kukkuta_kendra
      - SECRET_KEY=your-secret-key-for-development
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:19006
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=kukkuta_kendra
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend

volumes:
  postgres_data: 