name: Build and deploy backend to Azure Web App - kukkuta-kendra-app

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt

      - name: Upload backend artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: |
            backend/**
            !backend/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: 'Deploy backend to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kukkuta-kendra-app'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
